### ISSUE TITLE
i meet bug ,you meet this same bug ? 

### ISSUE THREAD

**Issue by rfyiamcool** [fluxchief/ahocorasick#1]
Apr  8 14:28:58 admaster abrt[15468]: Can't open /proc/23966/status: No such file or directory
Apr  8 14:28:59 admaster kernel: worker: extract[15388]: segfault at 7f881c46a000 ip 00007f881a1704d4 sp 00007fffd567afb0 error 4 in _ahocorasick.so[7f881a16f000+3000]
Apr  8 14:28:59 admaster abrt[15472]: Can't open /proc/23964/status: No such file or directory
Apr  8 14:29:01 admaster kernel: worker: extract[15432]: segfault at 2b46000 ip 00007f881a7a14d4 sp 00007fffd567afb0 error 4 in _ahocorasick.so[7f881a7a0000+3000]
Apr  8 14:29:01 admaster abrt[15485]: Can't open /proc/23999/status: No such file or directory
Apr  8 14:29:01 admaster kernel: worker: extract[15443]: segfault at 7f881bef5000 ip 00007f881a7a34d4 sp 00007fffd567afb0 error 4 in _ahocorasick.so[7f881a7a2000+3000]
Apr  8 14:29:01 admaster abrt[15488]: Can't open /proc/24006/status: No such file or directory
Apr  8 14:29:02 admaster kernel: worker: extract[15464]: segfault at 7f881c21f000 ip 00007f881a58a4d4 sp 00007fffd567afb0 error 4 in _ahocorasick.so[7f881a589000+3000]
Apr  8 14:29:02 admaster abrt[15494]: Can't open /proc/24021/status: No such file or directory
Apr  8 14:29:03 admaster kernel: worker: extract[15473]: segfault at 2b08000 ip 00007f881a16e4d4 sp 00007fffd567afb0 error 4 in _ahocorasick.so[7f881a16d000+3000]
Apr  8 14:29:03 admaster abrt[15503]: Can't open /proc/24028/status: No such file or directory

**Comment by fluxchief** [comment]
Did you use this fork or the official version?
